In [2]:
import pandas as pd
print(pd.__version__)

3.0.5

In [3]:
df_accounts = pd.read_csv("../data/raw/ravenstack_accounts.csv")
print(df_accounts.shape)
df_accounts.head()

(500, 10)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [4]:
df_subscriptions = pd.read_csv("../data/raw/ravenstack_subscriptions.csv")
print(df_subscriptions.shape)
df_subscriptions.head()

(5000, 14)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True

In [5]:
df_subscriptions.columns.tolist()

['subscription_id',
 'account_id',
 'start_date',
 'end_date',
 'plan_tier',
 'seats',
 'mrr_amount',
 'arr_amount',
 'is_trial',
 'upgrade_flag',
 'downgrade_flag',
 'churn_flag',
 'billing_frequency',
 'auto_renew_flag']

In [6]:
df_feature_usage = pd.read_csv("../data/raw/ravenstack_feature_usage.csv")
print(df_feature_usage.shape)
df_feature_usage.head()

(25000, 8)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

In [7]:
df_support = pd.read_csv("../data/raw/ravenstack_support_tickets.csv")
print(df_support.shape)
df_support.head()

(2000, 9)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

In [8]:
df_support.columns.tolist()

['ticket_id',
 'account_id',
 'submitted_at',
 'closed_at',
 'resolution_time_hours',
 'priority',
 'first_response_time_minutes',
 'satisfaction_score',
 'escalation_flag']

In [9]:
df_support = pd.read_csv("../data/raw/ravenstack_support_tickets.csv")
print(df_support.shape)
df_support.head()

(2000, 9)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

In [10]:
df_support.columns.tolist()

['ticket_id',
 'account_id',
 'submitted_at',
 'closed_at',
 'resolution_time_hours',
 'priority',
 'first_response_time_minutes',
 'satisfaction_score',
 'escalation_flag']

In [11]:
df_churn = pd.read_csv("../data/raw/ravenstack_churn_events.csv")
print(df_churn.shape)
df_churn.head()

(600, 9)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [12]:
df_churn.columns.tolist()

['churn_event_id',
 'account_id',
 'churn_date',
 'reason_code',
 'refund_amount_usd',
 'preceding_upgrade_flag',
 'preceding_downgrade_flag',
 'is_reactivation',
 'feedback_text']

In [13]:
print(df_churn.shape)

(600, 9)

In [14]:
df_churn['reason_code'].value_counts()

reason_code
features      114
support       104
budget        104
unknown        95
competitor     92
pricing        91
Name: count, dtype: int64

In [15]:
print(df_support.shape)

(2000, 9)

In [16]:
tables = {
    "accounts": df_accounts,
    "subscriptions": df_subscriptions,
    "feature_usage": df_feature_usage,
    "support_tickets": df_support,
    "churn_events": df_churn
}

for name, df in tables.items():
    print(f"--- {name} ---")
    print("Missing values:\n", df.isnull().sum())
    print("Duplicate rows:", df.duplicated().sum())
    print()

--- accounts ---
Missing values:
 account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64
Duplicate rows: 0

--- subscriptions ---
Missing values:
 subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64
Duplicate rows: 0

--- feature_usage ---
Missing values:
 usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64
Duplicate rows: 0

--- support_tickets ---
Missing values:
 ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64
Duplicate rows: 0

--- churn_events ---
Missing values:
 churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64
Duplicate rows: 0

In [17]:
for name, df in tables.items():
    print(name, "-> total missing values:", df.isnull().sum().sum(), "| duplicates:", df.duplicated().sum())

accounts -> total missing values: 0 | duplicates: 0
subscriptions -> total missing values: 4514 | duplicates: 0
feature_usage -> total missing values: 0 | duplicates: 0
support_tickets -> total missing values: 825 | duplicates: 0
churn_events -> total missing values: 148 | duplicates: 0

In [18]:
df_support.isnull().sum()

ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

In [19]:
df_accounts.dtypes

account_id           str
account_name         str
industry             str
country              str
signup_date          str
referral_source      str
plan_tier            str
seats              int64
is_trial            bool
churn_flag          bool
dtype: object

In [20]:
for name, df in tables.items():
    print(f"--- {name} ---")
    print(df.dtypes)
    print()

--- accounts ---
account_id           str
account_name         str
industry             str
country              str
signup_date          str
referral_source      str
plan_tier            str
seats              int64
is_trial            bool
churn_flag          bool
dtype: object

--- subscriptions ---
subscription_id        str
account_id             str
start_date             str
end_date               str
plan_tier              str
seats                int64
mrr_amount           int64
arr_amount           int64
is_trial              bool
upgrade_flag          bool
downgrade_flag        bool
churn_flag            bool
billing_frequency      str
auto_renew_flag       bool
dtype: object

--- feature_usage ---
usage_id                 str
subscription_id          str
usage_date               str
feature_name             str
usage_count            int64
usage_duration_secs    int64
error_count            int64
is_beta_feature         bool
dtype: object

--- support_tickets ---
ticket_id                          str
account_id                         str
submitted_at                       str
closed_at                          str
resolution_time_hours          float64
priority                           str
first_response_time_minutes      int64
satisfaction_score             float64
escalation_flag                   bool
dtype: object

--- churn_events ---
churn_event_id                  str
account_id                      str
churn_date                      str
reason_code                     str
refund_amount_usd           float64
preceding_upgrade_flag         bool
preceding_downgrade_flag       bool
is_reactivation                bool
feedback_text                   str
dtype: object

In [21]:
date_like_keywords = ["date", "_at"]

for name, df in tables.items():
    date_cols = [col for col in df.columns if any(k in col.lower() for k in date_like_keywords)]
    print(name, "->", date_cols)

accounts -> ['signup_date']
subscriptions -> ['start_date', 'end_date']
feature_usage -> ['usage_date']
support_tickets -> ['submitted_at', 'closed_at']
churn_events -> ['churn_date']

In [22]:
pd.to_datetime(df_accounts['signup_date']).min(), pd.to_datetime(df_accounts['signup_date']).max()

(Timestamp('2023-01-02 00:00:00'), Timestamp('2024-12-31 00:00:00'))

In [23]:
date_columns = {
    "accounts": ("signup_date", df_accounts),
    "subscriptions_start": ("start_date", df_subscriptions),
    "subscriptions_end": ("end_date", df_subscriptions),
    "feature_usage": ("usage_date", df_feature_usage),
    "support_submitted": ("submitted_at", df_support),
    "support_closed": ("closed_at", df_support),
    "churn_events": ("churn_date", df_churn)
}

for name, (col, df) in date_columns.items():
    converted = pd.to_datetime(df[col])
    print(name, "->", converted.min(), "to", converted.max())

accounts -> 2023-01-02 00:00:00 to 2024-12-31 00:00:00
subscriptions_start -> 2023-01-09 00:00:00 to 2024-12-31 00:00:00
subscriptions_end -> 2023-04-05 00:00:00 to 2024-12-31 00:00:00
feature_usage -> 2023-01-01 00:00:00 to 2024-12-31 00:00:00
support_submitted -> 2023-01-02 00:00:00 to 2024-12-31 00:00:00
support_closed -> 2023-01-03 03:00:00 to 2024-12-31 19:00:00
churn_events -> 2023-01-25 00:00:00 to 2024-12-31 00:00:00